apiVersion: v1
kind: Service
metadata:
  name: hugo-site
  labels:
    app: hugo-site
    tier: frontend
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32321
  selector:
    app: hugo-site
    tier: frontend